name: openid_client
description: Library for working with OpenID Connect and implementing clients.
version: 0.3.0
authors:
  - Rik Bellens <rik.bellens@appsup.be>
  - Ivan Matkov <ivan.matkov@akvelon.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  jose: ^0.1.2
  http: ^0.12.0
  logging: ^0.11.3+2
  flutter_custom_tabs: ^0.6.0
  uni_links: ^0.1.4

dev_dependencies:
  test: ^1.0.0
  build_runner: ">=0.8.10 <0.11.0"

executables:
  openid_client: openid_client